stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xiechuyu/git-sync:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: reg.ebcpaas.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: "0"
    notifier: c-mthlx:n-svr94
  condition:
  - Success
  - Changed
  - Failed
