common:
  frequency: "@hourly"
  is_force: false
  is_sync_tags: false
repos:
  - origin: "http://gitlab.ebcpaas.com/ebcpaas/ui-icons.git"
    origin_branch: "master"
    target: "https://github.com/Okabe-Kurisu/ui-icons.git"
    target_branch: "synctest"
auths:
  - group: "https://github.com/Okabe-Kurisu/"
    username: "username"
    password: "password"
  - group: "http://gitlab.ebcpaas.com/"
    username: "username"
    password: "password"
