apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: prun
spec:
  minReadySeconds: 120
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: git-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
        - image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: IfNotPresent
          name: git-sync
          resources: {}
          securityContext:
            capabilities: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - github.com
        ip: 25.6.204.3
      - hostnames:
        - git.rancher.io
        ip: 25.6.204.3
      hostNetwork: true
      nodeName: region2-worker04
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30